version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  web:
    build:
      context: ./api_barq/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "python manage.py migrate --run-syncdb  && python manage.py runserver 0.0.0.0:8000"
